import mongoose from "mongoose";

const messageSchema = new mongoose.Schema({
    //expecting an ObjectId typically generated by MongoDB for uniquely identifying documents in a collection
    senderId : {
        type : mongoose.Schema.Types.ObjectId,
        ref : "User",
        required : true
    },
    
    receiverId : {
        type : mongoose.Schema.Types.ObjectId,
        ref : "User",
        required : true
    },

    message : {
        type : String,
        required : true 
    }
    //createdAt and updatedAt
},{timestamps: true});

const Message = mongoose.model("Message", messageSchema);

export default Message;